project:
  type: sdca-theme

website:
  title: "LIVING forskningsprojekt"
  site-url: "https://jonasmunkjensen.github.io/StenOrg/"
  repo-url: "https://jonasmunkjensen.github.io/StenOrg/"
  page-navigation: true
  search: true

  page-footer:
    right: "Denne hjemmeside er lavet i [Quarto](https://quarto.org/)."

  navbar:
    background: light
    logo: logo.PNG
    logo-alt: Steno Diabetes Center Aarhus
    title: false
    tools:
      - icon: github
        href: https://github.com/Jonasmunkjensen/StenOrg
        text: "StenOrg"
    collapse-below: lg
    left:
      - text: "Forside"
        href: index.qmd
      - text: "Kontakt"
        href: 0-kontakt.qmd
      - text: "How to hjemmeside"
      - href: 1-hot_to.qmd

format:
  sdca-theme-html:
    theme:
      - brand
      - custom-styles.scss

editor:
  markdown:
    wrap: 72
    canonical: true
