project:
  type: website

website:
  title: "LIVING forskningsprojekt"
  site-url: "https://jonasmunkjensen.github.io/StenOrg/"
  repo-url: "https://jonasmunkjensen.github.io/StenOrg/"
  page-navigation: true
  search: true

  page-footer:
    right: "Denne hjemmeside er lavet i [Quarto](https://quarto.org/)."

  navbar:
    background: light
    logo: logo.PNG
    logo-alt: Steno Diabetes Center Aarhus
    title: false
    tools:
      - icon: github
        href: https://github.com/Jonasmunkjensen/StenOrg
        text: "StenOrg"
    collapse-below: lg
    left:
      - text: "Forside"
        href: index.qmd
      - text: "Kontakt"
        href: 0-kontakt.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    toc: true
